baseURL = 'https://www.abdisalam.blog/'
defaultContentLanguage = 'en'
title = 'Don Abdisalam | The Website'

[languages.en]
locale = 'en-US'
label = 'English'
weight = 1

[taxonomies]
  tag = "tags"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    noClasses = false
    guessSyntax = true

[server]
  watch = false

[build]
  noJSConfigInAssets = true
  buildFuture = true

[params]
mainSections = ["blog"]
author = "Don Abdisalam"
htmlLang = "en-US"
